spring:
  datasource:
    url: jdbc:mysql://localhost:3306/budget?createDatabaseIfNotExist=true
    username: root
    password: 1234567a
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml

logging:
  level:
    org:
      jooq: DEBUG
